import type { Metadata } from "next";
import "../globals.css";
import SmallMainBar from "../components/mainbars/SmallMainBar";
import LargeMainBar from "../components/mainbars/LargeMainBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-screen bg-[#0A1628] p-10 text-white font-sans">

        {/* Main Layout */}
        <div className="flex min-h-screen">

          {/* Desktop Left Sidebar */}
          <aside className="hidden lg:flex lg:w-70 lg:fixed lg:left-0 lg:top-0 lg:h-screen border-r border-white/10">
            <LargeMainBar />
          </aside>

          {/* Right Content Area */}
          <main className="flex-1 lg:ml-70 min-h-screen px-4 pb-24 pt-2">
            {children}
          </main>

        </div>

        {/* Mobile Bottom Navigation */}
        <div className="fixed bottom-2 left-0 z-50 w-full lg:hidden">
          <SmallMainBar />
        </div>

      </body>
    </html>
  );
}