import type { Metadata } from "next";
import "../globals.css";
import SmallMainBar from "../components/mainbars/SmallMainBar";
import LargeMainBar from "../components/mainbars/LargeMainBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-screen bg-[#0A1628] text-white font-sans">

        {/* Desktop main sidebar/header */}
        <div className="hidden lg:flex">
          <LargeMainBar />
        </div>

        {/* Page content */}
        <main className="min-h-screen px-4 pb-24 pt-2">
          {children}
        </main>

        {/* Mobile bottom nav */}
        <div className="fixed bottom-2 left-0 z-50 w-full lg:hidden">
          <SmallMainBar />
        </div>

      </body>
    </html>
  );
}