import type { Metadata } from "next"
import "../globals.css"

import LargeMainBar from "../components/mainbars/LargeMainBar"
import SmallMainBar from "../components/mainbars/SmallMainBar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-screen bg-[#0A1628] text-white font-sans">

        {/* ===== APP SHELL LAYOUT ===== */}
        <div className="min-h-screen">

          {/* Desktop Sidebar */}
          <aside className="hidden lg:block w-70 fixed left-0 top-0 h-screen border-r border-white/10 bg-[#08111F]/95 backdrop-blur-2xl">
            <LargeMainBar />
          </aside>

          {/* Main Content */}
          <main className="min-h-screen lg:ml-70 px-4 pb-24 pt-2">
            {children}
          </main>

        </div>

        {/* Mobile Bottom Navigation */}
        <div className="fixed bottom-2 left-0 z-50 w-full lg:hidden">
          <SmallMainBar />
        </div>

      </body>
    </html>
  )
}