import type { Metadata } from "next";
import "../globals.css";
import SmallGlobalBar from "../components/globalbars/SmallGlobalBar";
import LargeGlobalBar from "../components/globalbars/LargeGlobalBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-screen bg-[#0A1628] text-white font-sans">

        {/* DESKTOP NAVBAR */}
        <div className="hidden lg:flex fixed top-0 left-0 w-full z-50 backdrop-blur-xl bg-[#0A1628]/60 border-b border-white/10">
          <LargeGlobalBar />
        </div>

        {/* MAIN CONTENT */}
        <main className="min-h-screen lg:px-15 pb-28 lg:pt-28 pt-2">
          {children}
        </main>

        {/* MOBILE FLOATING BOTTOM NAVBAR */}
        <div className="fixed bottom-2 left-0 z-50 w-full px-4 lg:hidden">
          
          {/* Blur background */}
          <div className="backdrop-blur-xl bg-[#0A1628]/60 border border-white/10 rounded-2xl shadow-2xl">
            <SmallGlobalBar />
          </div>

        </div>

      </body>
    </html>
  );
}