import type { Metadata } from "next";
import "../globals.css";
import SmallGlobalBar from "../components/globalbars/SmallGlobalBar";
import LargeGlobalBar from "../components/globalbars/LargeGlobalBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-screen bg-[#0A1628] text-white font-sans">

        <div className="hidden lg:flex fixed top-0 left-0 w-full z-50 backdrop-blur-xl bg-[#0A1628]/60 border-b border-white/10">
          <LargeGlobalBar />
        </div>

        <main className="min-h-screen lg:px-15 pb-28 lg:pt-28 pt-2">
          {children}
        </main>

      </body>
    </html>
  );
}